# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e65a8ea00942a87a8327c0c989ab9054c3f22c05fe4e375a04c646e9ab956fc8a473689bf6611621cfea7ce9261a2c3a6ab25e84954ed79c815d091ca5d4e8f6

test:
  secret_key_base: 6a8f719fb7822822e55169a4a87f521267773cbd37dbcffdf8d616019feca35389052c5d727e7316b05cb9f4bcfbd4f9e1fa9b5382c7120ec602aa447784d639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
